theme = "lynx"
title = "joypaulsen.com"

enableEmoji = true
disableKinds = ["taxonomy", "term"]

[params.author]
name = "Joy Paulsen"
headline = "Data Scientist, Engineer, & Builder"
# image = "author.jpg"
links = [
  { link = { href = "bio/", text = "Bio", target = "_self" } },
  # { link = { href = "https://joypauls.dev/", text = "Blog", target = "_blank" } },
  { linkedin = "https://linkedin.com/in/joy-paulsen-0bb55419b" },
  { github = "https://github.com/joypauls" },
  { email = "mailto:hello@joypauls.dev" },
]

[markup.highlight]
noClasses = false

[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true
